### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by mcmire**
See changelog.

### CODE REVIEW

**Comment by mcmire** [comment]
This PR is blocked by setting up an NPM integration token for this repo.

**Comment by Gudahtt** [comment]
>This PR is blocked by setting up an NPM integration token for this repo.

We'll have to do the first release manually. We're using scoped tokens now, and they can't be generated before the first publish.

**Comment by mcmire** [comment]
Ah! Gotcha. I imagine that's why you mentioned that as a possibility initially.

**Comment by Gudahtt** [comment]
Thoughts on making this v2 instead, to avoid any confusion with the rename?

**Comment by mcmire** [comment]
> Thoughts on making this v2 instead, to avoid any confusion with the rename?

Okay, yup, that's a good idea.

> We'll have to do the first release manually. 

Should I remove the release workflow for now so that we can merge this PR? Otherwise it'll hang.

**Comment by Gudahtt** [comment]
>Should I remove the release workflow for now so that we can merge this PR? Otherwise it'll hang.

It should just treat the npm-publish step as a dry run if the token is missing. Elsewhere we've just let that run through, and I've published manually and setup the token afterwards.

**Comment by mcmire** [comment]
@Gudahtt Ah, yes. You're right.

I've bumped the version to 2.0.0 here: [e1f8e9b](https://github.com/MetaMask/swappable-obj-proxy/pull/24/commits/e1f8e9b97027c8595d10fe3fb4d8b40d02463332)

**Comment by Gudahtt** [comment]
Do any of our release automation steps use the branch name? I recall it used to, but I don't remember which part. This branch name still has the version 1.0.0

**Comment by mcmire** [comment]
@Gudahtt That's a good question, and I looked into that briefly. It seems that we changed `action-publish-release` a while back to read the version from the `package.json` instead of from the release branch: https://github.com/MetaMask/action-publish-release/pull/46. `action-npm-publish` also just looks at the `package.json` since this PR: https://github.com/MetaMask/action-npm-publish/pull/5. So as long as we use the latest versions of these actions I don't think we need to worry about the name of the branch anymore. Does that sound right?

**Review by Gudahtt — APPROVED** [review]
Nice! Ok, well I know one way to find out

**Comment by mcmire** [comment]
@Gudahtt That didn't work, but it's not because of the branch name, it's because I ended up creating the release branch manually (because at the time it made sense, since we were going from 1.1.0 -> 1.0.0) and [this line](https://github.com/MetaMask/swappable-obj-proxy/blob/main/.github/workflows/main.yml#L58) stopped it. I'll revert this PR and re-create it.

**Pull request merged**
